url: 'https://test-stand.gb.ru/gateway/login'
url1: 'https://test-stand.gb.ru/api/posts'
username: 'Finik'
password: '70ccea8a70'

title: 'Title_hw1'
description: 'homework1'
content: 'homeworkContent1'

